// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHYvMEVmjhyNyqSeLsXCLhhBuKrtbIrXc',
    appId: '1:1026874312162:web:772155923e086f901de5bb',
    messagingSenderId: '1026874312162',
    projectId: 'mj-flutter-app',
    authDomain: 'mj-flutter-app.firebaseapp.com',
    storageBucket: 'mj-flutter-app.appspot.com',
    measurementId: 'G-ZL17BG9VHE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj4qvKQy2If0TAkpmW5soTBvNTlLIsD9Y',
    appId: '1:1026874312162:android:7b53ab71a5dd58001de5bb',
    messagingSenderId: '1026874312162',
    projectId: 'mj-flutter-app',
    storageBucket: 'mj-flutter-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd-ZIqvOu1A6pT-QH1BZEGpYvpSkkKbKs',
    appId: '1:1026874312162:ios:751092521014bef21de5bb',
    messagingSenderId: '1026874312162',
    projectId: 'mj-flutter-app',
    storageBucket: 'mj-flutter-app.appspot.com',
    iosClientId: '1026874312162-e1oa3l5gtr4f6376ea9abfl15u3kf4he.apps.googleusercontent.com',
    iosBundleId: 'com.example.myNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCd-ZIqvOu1A6pT-QH1BZEGpYvpSkkKbKs',
    appId: '1:1026874312162:ios:c129378595919b001de5bb',
    messagingSenderId: '1026874312162',
    projectId: 'mj-flutter-app',
    storageBucket: 'mj-flutter-app.appspot.com',
    iosClientId: '1026874312162-43o7aqpki5bnage4dcc7vo8f9l5p5i7m.apps.googleusercontent.com',
    iosBundleId: 'com.example.myNotes.RunnerTests',
  );
}
